services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev   # use a dev Dockerfile with Air
    volumes:
      - .:/app
      - air_cache:/go/pkg/mod      # cache dependencies
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    networks:
      - backend

volumes:
  air_cache:

networks:
  backend:
    driver: bridge
